#    __ ___ __  __
#   / //_(_) /_/ /___ __
#  / ,< / / __/ __/ // /
# /_/|_/_/\__/\__/\_, /
#                /___/
#
# Configuration based on:
# https://github.com/kovidgoyal/kitty-themes/blob/master/themes/GitHub_Dark.conf
# Adjusted by me
#
# You can find the normal configuration (without the NixOS color scheme) at:
# https://github.com/lords1nister1/.config/blob/b53b27e21fa47da0250d998ad3fc86f0b8af4711/kitty/kitty.conf

font_family                 JetBrainsMono Nerd Font
font_size                   12
bold_font                   auto
italic_font                 auto
bold_italic_font            auto
remember_window_size        no
initial_window_width        1175
initial_window_height       525
cursor_blink_interval       0.5
cursor_stop_blinking_after  1
scrollback_lines            2000
wheel_scroll_min_lines      1
enable_audio_bell           no
window_padding_width        10
hide_window_decorations     yes
confirm_os_window_close     0
background_opacity          0.7
dynamic_background_opacity  yes
foreground                  #c9d1d9
background                  #0d1117
selection_foreground        #0d1117
selection_background        #58a6ff
cursor                      #58a6ff
tab_bar_background          #010409
active_tab_foreground       #c9d1d9
active_tab_background       #0d1117
inactive_tab_foreground     #8b949e
inactive_tab_background     #010409
color0                      #484f58
color1                      #ff7b72
color2                      #3fb950
color3                      #d29922
color4                      #58a6ff
color5                      #bc8cff
color6                      #39c5cf
color7                      #b1bac4
color8                      #6e7681
color9                      #ffa198
color10                     #56d364
color11                     #e3b341
color12                     #79c0ff
color13                     #d2a8ff
color14                     #56d4dd
color15                     #ffffff
