Gdk/UnscaledDPI 98304
Gdk/WindowScalingFactor 1
Gtk/EnableAnimations 1
Gtk/DecorationLayout "icon:minimize,maximize,close"
Net/ThemeName ""
Gtk/PrimaryButtonWarpsSlider 1
Gtk/ToolbarStyle 0
Gtk/MenuImages 0
Gtk/ButtonImages 0
Net/CursorBlinkTime 1000
Net/CursorBlink 1
Gtk/CursorThemeSize 24
Gtk/CursorThemeName "breeze_cursors"
Net/SoundThemeName ""
Net/IconThemeName "breeze-dark"
Gtk/FontName "Noto Sans,  10"

