[General]
x=0
y=0

[caching]
lastCacheFileHash=@ByteArray(e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855)
lastDownloadSHA256=@ByteArray(19b108fe07cff2b5cd7df0f76b6d7325e43fb2a1d5418d10f6bd56642e0e8579)
lastFileName=/home/user/.cache/Raspberry Pi/Raspberry Pi Imager/lastdownload.cache

[imagecustomization]
capitalCity=Vienna (Austria)
hostname=raspberrypi4
keyboard=at
recommendedWifiCountry=AT
sshEnabled=true
sshPasswordAuth=true
sshUserName=user
sshUserPassword=$y$jB5$MVrB6FKKpZ4Al7aFIZqQ2/$Lrtw1Q/5fjQRkjrx9pJaEYRafRoZ/wqsf7bBZE4/cND
timezone=Europe/Vienna
wifiHidden=false
wifiMode=secure
wifiPasswordCrypt=11b45f649dae95d8b7874a994f3d54ce3e6ff22e33037aeb2eaa53f6545f1788
wifiSSID=HUAWEI-E5180-28D7
