[General]
x=926
y=45

[caching]
lastCacheFileHash=@ByteArray(f7afb40e587746128538d84f217bf478a23af59484d4db77f2d06bf647f7c82e)
lastDownloadSHA256=@ByteArray(19b108fe07cff2b5cd7df0f76b6d7325e43fb2a1d5418d10f6bd56642e0e8579)
lastFileName=/home/user/.cache/Raspberry Pi/Raspberry Pi Imager/lastdownload.cache

[imagecustomization]
capitalCity=Vienna (Austria)
hostname=raspberrypi
keyboard=at
recommendedWifiCountry=AT
sshEnabled=true
sshPasswordAuth=true
sshUserName=user
sshUserPassword=$y$jB5$27rJndpMtsmBKN2Ga73Pj/$d8/wvo5AupQRbBxtQUkR32xrq/5dh3UYBgMsXCe52m2
timezone=Europe/Vienna
wifiHidden=false
wifiMode=secure
wifiPasswordCrypt=11b45f649dae95d8b7874a994f3d54ce3e6ff22e33037aeb2eaa53f6545f1788
wifiSSID=HUAWEI-E5180-28D7
